version: '3'

services:
  redis:
    image: redis

  ping:
    build: .
    command: ping
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  pong:
    build: .
    command: pong
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis